In [154]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [171]:
dataset = pd.read_csv('D:\Data.csv')

In [172]:
dataset

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [173]:
dataset = dataset.dropna(axis=1)

In [174]:
#Count of Malignant(M) and Benign(B)
dataset['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [183]:
#Encoding the categorical data 
from sklearn.preprocessing import LabelEncoder
labelencoder_Y = LabelEncoder()
dataset.iloc[:,1] = labelencoder_Y.fit_transform(dataset.iloc[:,1].values)
print(labelencoder_Y.fit_transform(dataset.iloc[:,1].values))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1
 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0
 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1
 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0
 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 1 0 0 1 

In [176]:
#Splitting data into independent(X) and dependent(Y) datasets
X = dataset.iloc[:,2:31].values
Y = dataset.iloc[:,1].values

In [177]:
#Splitting data into train:test ratio 70:30
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.30,random_state=0)

In [178]:
#Scaling the data
from sklearn.preprocessing import StandardScaler
ssc = StandardScaler()
X_train = ssc.fit_transform(X_train)
X_test = ssc.fit_transform(X_test)


In [179]:
def models(X_train,Y_train):
  
  #Using KNeighborsClassifier(KNN) 
    from sklearn.neighbors import KNeighborsClassifier
    knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    knn.fit(X_train, Y_train)

  #Using Naive Bayes 
    from sklearn.naive_bayes import GaussianNB
    gauss = GaussianNB()
    gauss.fit(X_train, Y_train)

  #Using DecisionTreeClassifier 
    from sklearn.tree import DecisionTreeClassifier
    destree = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    destree.fit(X_train, Y_train)

  #Using Random Forest Classifier 
    from sklearn.ensemble import RandomForestClassifier
    fore = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    fore.fit(X_train, Y_train)
  
    print('0.K Nearest Neighbor Training Accuracy:', knn.score(X_train, Y_train))
    print('1.Gaussian Naive Bayes Training Accuracy:', gauss.score(X_train, Y_train))
    print('2.Decision Tree Classifier Training Accuracy:', destree.score(X_train, Y_train))
    print('3.Random Forest Classifier Training Accuracy:', fore.score(X_train, Y_train))
  

    return  knn, gauss, destree, fore

In [180]:
model = models(X_train,Y_train)

0.K Nearest Neighbor Training Accuracy: 0.9723618090452262
1.Gaussian Naive Bayes Training Accuracy: 0.9447236180904522
2.Decision Tree Classifier Training Accuracy: 1.0
3.Random Forest Classifier Training Accuracy: 0.9949748743718593


In [181]:
#test model accuracy 


from sklearn.metrics import confusion_matrix

for i in range(len(model)):
    
    print('Model ',i)
    com = confusion_matrix(Y_test, model[i].predict(X_test))
  
    TP = cm[0][0]
    TN = cm[1][1]
    FN = cm[1][0]
    FP = cm[0][1]
  
    print(com)
    print('Testing Accuracy = ', (TP + TN) / (TP + TN + FN + FP))
    print()

Model  0
[[104   4]
 [  6  57]]
Testing Accuracy =  0.9590643274853801

Model  1
[[99  9]
 [ 6 57]]
Testing Accuracy =  0.9590643274853801

Model  2
[[102   6]
 [  4  59]]
Testing Accuracy =  0.9590643274853801

Model  3
[[106   2]
 [  5  58]]
Testing Accuracy =  0.9590643274853801



In [166]:

#We have now created a breast detection program to predict if a patient has cancer or not.According to the data above, the most 
#accurate value was provided by Random Forest Classifier algorithm with accuracy of 95.90%. Hence, the best suited algorithm for 
#this task is the Random Forest Classifier algorithm.


In [ ]:
#Thank you